import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
    title: 'Create MTG',
    description: 'Generated by create MTG',
};

const RootLayout = async ({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) => {
    return (
        <html lang='en'>
            <body >

                {children}

            </body>
        </html>
    );
};

export default RootLayout;